version: '3'
services:
  # redis_server:
  #   image: "redis"
  #   ports:
  #     - "6379:6379"
  server_6001:
    build:
      context: ./dockerfile
      dockerfile: node1_Dockerfile
    volumes:
      - './redis/redis-config-1:/src/redis/redis-config'
    ports:
      - '6001:6001'
      - '16001:16001'
    command:
      "./redis/redis-config/cmd.sh"
  server_6002:
    build:
      context: ./dockerfile
      dockerfile: node2_Dockerfile
    volumes:
      - './redis/redis-config-2:/src/redis-2/redis-config'
    ports:
      - '6002:6002'
      - '16002:16002'
    command:
      "./redis-2/redis-config/cmd.sh"
  server_6003:
    build:
      context: ./dockerfile
      dockerfile: node3_Dockerfile
    volumes:
      - './redis/redis-config-3:/src/redis-3/redis-config'
    ports:
      - '6003:6003'
      - '16003:16003'
    command:
      "./redis-3/redis-config/cmd.sh"
  server_6004:
    build:
      context: ./dockerfile
      dockerfile: node4_Dockerfile
    volumes:
      - './redis/redis-config-4:/src/redis-4/redis-config'
    ports:
      - '6004:6004'
      - '16004:16004'
    command:
      "./redis-4/redis-config/cmd.sh"
  server_6005:
    build:
      context: ./dockerfile
      dockerfile: node5_Dockerfile
    volumes:
      - './redis/redis-config-5:/src/redis-5/redis-config'
    ports:
      - '6005:6005'
      - '16005:16005'
    command:
      "./redis-5/redis-config/cmd.sh"
  server_6006:
    build:
      context: ./dockerfile
      dockerfile: node6_Dockerfile
    volumes:
      - './redis/redis-config-6:/src/redis-6/redis-config'
    ports:
      - '6006:6006'
      - '16006:16006'
    command:
      "./redis-6/redis-config/cmd.sh"
# version: '3'

# services:
#   redis-master:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6379'
#     environment:
#       - REDIS_REPLICATION_MODE=master
#       - REDIS_PASSWORD=my_master_password
#     volumes:
#       - '/path/to/redis-persistence:/bitnami'
#   redis-replica:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6379'
#     depends_on:
#       - redis-master
#     environment:
#       - REDIS_REPLICATION_MODE=slave
#       - REDIS_MASTER_HOST=redis-master
#       - REDIS_MASTER_PORT_NUMBER=6379
#       - REDIS_MASTER_PASSWORD=my_master_password
#       - REDIS_PASSWORD=my_replica_password

