version: '3'
services:
  # redis_server:
  #   image: "redis"
  #   ports:
  #     - "6379:6379"
  server_6001:
    build:
      context: ./dockerfile
      dockerfile: node1_Dockerfile
    volumes:
      - './redis/redis-config-1:/src/redis/redis-config'
    ports:
      - '6001'
    # command:
    #   "redis-server /redis.conf"
  server_6002:
    build:
      context: ./dockerfile
      dockerfile: node2_Dockerfile
    volumes:
      - './redis/redis-config-2:/src/redis-2/redis-config'
    ports:
      - '6002'
    # command:
    #   "./redis/redis-config-2/cmd.sh"
  server_6003:
    build:
      context: ./dockerfile
      dockerfile: node3_Dockerfile
    volumes:
      - './redis/redis-config-3:/src/redis-3/redis-config'
    ports:
      - '6003'
    # command:
    #   "./redis/redis-config-3/cmd.sh"
  server_6004:
    build:
      context: ./dockerfile
      dockerfile: node4_Dockerfile
    volumes:
      - './redis/redis-config-4:/src/redis-4/redis-config'
    ports:
      - '6004'
    # command:
    #   "./redis/redis-config-4/cmd.sh"
  server_6005:
    build:
      context: ./dockerfile
      dockerfile: node5_Dockerfile
    volumes:
      - './redis/redis-config-5:/src/redis-5/redis-config'
    ports:
      - '6005'
    # command:
    #   "./redis/redis-config-5/cmd.sh"
  server_6006:
    build:
      context: ./dockerfile
      dockerfile: node6_Dockerfile
    volumes:
      - './redis/redis-config-6:/src/redis-6/redis-config'
    ports:
      - '6006'
    # command:
    #   "./redis/redis-config-6/cmd.sh"
# version: '3'

# services:
#   redis-master:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6379'
#     environment:
#       - REDIS_REPLICATION_MODE=master
#       - REDIS_PASSWORD=my_master_password
#     volumes:
#       - '/path/to/redis-persistence:/bitnami'
#   redis-replica:
#     image: 'bitnami/redis:latest'
#     ports:
#       - '6379'
#     depends_on:
#       - redis-master
#     environment:
#       - REDIS_REPLICATION_MODE=slave
#       - REDIS_MASTER_HOST=redis-master
#       - REDIS_MASTER_PORT_NUMBER=6379
#       - REDIS_MASTER_PASSWORD=my_master_password
#       - REDIS_PASSWORD=my_replica_password